version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # 将容器的80端口映射到主机的8000端口
    volumes:
      - .:/app  # 挂载当前目录到容器的工作目录
    environment:
      - REDIS_HOST=redis  # Redis 主机名指向 redis 服务
      - REDIS_PORT=6379
      - OAUTH2_CLIENT_ID=your_client_id
      - OAUTH2_CLIENT_SECRET=your_client_secret
      - OAUTH2_REDIRECT_URI=http://localhost:8000/auth/callback
      - OAUTH2_PROVIDER_URL=https://github.com/login/oauth
      - SECRET_KEY=your-secret-key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - redis  # 确保 redis 容器先启动

  redis:
    image: "redis:alpine"  # 使用轻量级的 Redis Alpine 镜像

