version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # 将容器的80端口映射到主机的8000端口
    volumes:
      - .:/app  # 挂载当前目录到容器的工作目录
    env_file:
      - .env
    depends_on:
      - redis  # 确保 redis 容器先启动

  redis:
    image: "redis:alpine"  # 使用轻量级的 Redis Alpine 镜像

